### ISSUE TITLE
this.render() is not a function error

### ISSUE THREAD

**Issue by HiggsOfChaos** [hull/hull-js#136]
Hi have a component that changes templates on certain events. I am using this as a way to route between views.
<code>
Hull.component("app",{

```
templates: [
    'main',
    'pics',
    'users',
    'upload',
    'battle'

],

initialize: function () {
    console.log("APP view rendered");

    Hull.on("xroute",function(newroute){
        this.template = newroute;
        console.log("Router triggered with " + newroute);
        this.refresh();
    });
},

appRouter: function (newroute) {

},


afterRender:function () {
    $(".route").on("click",function(){

    var data = $( this ).data('route');

        Hull.emit('xroute',data);
    })
}
```

});

</code>

The problem is anytime the event is fired, the message is looged to the console showing the event was caught but any method I call after that give an error that "this is not a function".

It doesnt matter if it is the in-built render method or my own appRouter method - same result. I am sure I am missing something simple here, but cant seem to get it.

**Comment by KishanMaurya** [comment]
@sbellity  app.js:19 Uncaught TypeError: render is not a function
    

`_I am using vanilla js_ ` please help me 
![Screenshot_24](https://user-images.githubusercontent.com/45098599/97843476-60c26680-1d0f-11eb-8d12-65051bbe4c46.png)
